### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by spotlesscoder** [noteed/rescoyl#1]
What problems does this registry solve? 

This is not clearly stated on the Readme page

I have no idea what I could use this for.

Best regards

**Comment by noteed** [comment]
This solves (solved) the same problem as the official Docker registry, simply hosting Docker images. This uses the protocol v1 (I think I have some bits of protocol v2 in a branch) so this is currently mostly obsolete.

The point of this implementation was having something easily useable as a library in Haskell projects.
